%.filtered.vcf:Q: %.vcf.gz
	echo "[DEBUG] filtering vcf"
	number_of_samples=$(bcftools view -h $prereq | tail -n1 | cut -f10- | tr "\t" "\n" | wc -l)
	echo "[DEBUG] number of samples is: $number_of_samples"
	max_an=$((number_of_samples * 2))
	echo "[DEBUG] max_an is: $max_an"
	## keep only variants with max AN - i.e. no missing data
	## keep only SNPS
	## remove singletons and private alleles
	bcftools view \
		--include "AN>=$max_an" \
		--types snps \
		$prereq \
	| bcftools view \
		--min-ac 2 \
		--exclude 'INFO/AC == 2 & GT="AA"' > $target
